### ISSUE TITLE
Kyle Wynne Peer Review

### ISSUE THREAD

**Issue by KyleWynne** [PatrickPolcuch/CPSC354Project#1]
Hi guys I really like how the project is coming along. I went ahead and created the basic structure and framework for a repeat measure block. I think this block would really help the ease of use for the project. It's included in my pull request.

Also I noticed the landing page for your github site is the readme, I have found a way to put an automatic redirect to the src file. If you want help with that let me know its a really quick change.

**Comment by spencerlafferty2020** [comment]
Hey Kyle. I love the idea of a repeat measure. I'll check out the pull request, but there's a couple ways I could think of to implement the idea. One that just repeats the last measure, or one that references a common block (like a chorus). Thanks for your suggestion.
