### ISSUE TITLE
Lauren Szlosek - Peer Review

### ISSUE THREAD

**Issue by laurenszlosek** [PatrickPolcuch/CPSC354Project#5]
Hi guys! I lucked out and got to watch this group's presentation and I think it's super interesting. I had never seen anyone connect sound to javascript before. As for actual feedback, my only addition would be to add more to your readme for others who may want to contribute to the project in the future. Because I've also been working on a blockly project this semester I understood the basic steps to add blocks but I wasn't really sure what to do from there. I know the project is able to create music because of the demo but I wasn't really sure how to do that on my end. Regardless, that's an easy fix! For my pull request, I went ahead and added a block that I thought might make the project slightly more customizable. The "dynamic block" in theory should let the user choose a specific marking for each note. This could be good for the eventual creation of sheet music. Good luck with the rest of your project!

**Comment by JustinLee27** [comment]
Thank you for your feedback! We are glad you find our project interesting! We will be adjusting our README to better explain our project and make it easier for people to navigate the github. Thank you for the pull request as well, we will do our best to incorporate it into our project with your ideas in mind. We plan on adding sheet music generation potentially later down the line, however, for now we will find other ways to include the dynamic block. Thank you again!
